=== sharad-ghimire/Dairy-Keeper-Labs-JSP/web/WEB-INF/diary.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.uts.edu.au/31284/wsd-diary" 
    xmlns="http://www.uts.edu.au/31284/wsd-diary" elementFormDefault="qualified">    <!-- Insert your type declarations here -->
    <xs:simpleType name="ratingType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1" />
            <xs:maxInclusive value="5"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="dateType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{1,2}/\d{1,2}/\d{1,4}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="nameType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][a-zA-Z ]*"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="emailType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z.]*@[a-z]{2,7}\\.[a-z]{2,6}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="diary">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="profile" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="nameType"/>
                            <xs:element name="introduction" type="xs:string"/>
                            <xs:element name="dob" type="dateType"/>
                            <xs:element name="email" type="xs:string"/>
                            <xs:element name="interests" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="interest" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="name" type="xs:string"/>
                                                    <xs:element name="description" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="entry" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="date" type="dateType"/>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="rating" type="ratingType"/>
                            <xs:element name="body" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== sharad-ghimire/Dairy-Keeper-Labs-JSP/build/web/WEB-INF/diary.xml
<?xml version="1.0" encoding="UTF-8"?>
<diary xmlns="http://www.uts.edu.au/31284/wsd-diary" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.uts.edu.au/31284/wsd-diary diary.xsd">

    <profile>
        <name>Sammy Kohg</name>
        <introduction>  
            Hi, I'm Sammy and I'm an IT student at the University of Technology, Sydney.
            I'm originally from Germany, and I decided to start this diary to practice
            my English.
        </introduction>
        <dob>1/1/2000</dob>
        <email>Sammy.Kohg@gmail.com</email>
        <interests>
            <interest>
                <name>Football</name>
                <description>A ball game.</description>
            </interest>
            <interest>
                <name>TV</name>
                <description>I like to watch the football show.</description>
            </interest>
        </interests>
    </profile>
    <entry>
        <date>15/9/2012</date>
        <title>I bought a new phone</title>
        <rating>3</rating>
        <body>
            Today I bought a Galaxy S III to replace my old iPhone.
        </body>
    </entry>
    <entry>
        <date>16/10/2012</date>
        <title>Busy day</title>
        <rating>5</rating>
        <body>
            I have 3 assignments due today. I need coffee!
        </body>
    </entry>
</diary>
